from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    WAITING = "waiting"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


class CandidateStatus(StrEnum):
    GENERATED = "generated"
    PPL_SCORED = "ppl_scored"
    STRUCTURE_QUEUED = "structure_queued"
    STRUCTURE_SCORED = "structure_scored"
    ROSETTA_QUEUED = "rosetta_queued"
    ROSETTA_SCORED = "rosetta_scored"
    SELECTED = "selected"
    MUTATED = "mutated"
    REJECTED = "rejected"
    FAILED = "failed"


class EvaluationStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    UNSUPPORTED = "unsupported"


class MetricName(StrEnum):
    CONDITIONAL_NLL = "conditional_nll"
    CONDITIONAL_PPL = "conditional_ppl"
    INSTABILITY_INDEX = "instability_index"
    HYDROPHOBIC_FRACTION = "hydrophobic_fraction"
    MAXIMUM_HYDROPHOBIC_RUN = "maximum_hydrophobic_run"
    MAXIMUM_IDENTICAL_RESIDUE_RUN = "maximum_identical_residue_run"
    MOLECULAR_WEIGHT_DA = "molecular_weight_da"
    NET_CHARGE_PH7_4 = "net_charge_ph7_4"
    ISOELECTRIC_POINT = "isoelectric_point"
    GRAVY = "gravy"
    HYDROPHOBIC_MOMENT_EISENBERG = "hydrophobic_moment_eisenberg"
    CATIONIC_RESIDUE_FRACTION = "cationic_residue_fraction"
    BOLTZ2_CONFIDENCE = "boltz2_confidence"
    BOLTZ2_IPTM = "boltz2_iptm"
    BOLTZ2_PAIR_IPTM = "boltz2_pair_iptm"
    BOLTZ2_COMPLEX_IPLDDT = "boltz2_complex_iplddt"
    BOLTZ2_PAIR_IPTM_MEDIAN = "boltz2_pair_iptm_median"
    POCKET_CONTACT_COUNT = "pocket_contact_count"
    POCKET_CONTACT_CONSISTENCY = "pocket_contact_consistency"
    POCKET_COVERAGE_FRACTION = "pocket_coverage_fraction"
    OFF_POCKET_CONTACT_FRACTION = "off_pocket_contact_fraction"
    INTERFACE_MIN_DISTANCE_ANGSTROM = "interface_min_distance_angstrom"
    INTERFACE_CLASH_COUNT = "interface_clash_count"
    POSE_CLUSTER_FRACTION = "pose_cluster_fraction"
    STRUCTURE_AVAILABLE = "structure_available"
    STRUCTURE_SUPPORT = "structure_support"
    INTERFACE_GATE_PASS = "interface_gate_pass"
    PEPPAP_PKD_PKI = "peppap_pkd_pki"
    PEPPAP_DELTA_G_KCAL_MOL = "peppap_delta_g_kcal_mol"
    PEPPAP_KD_EQUIVALENT_MOLAR = "peppap_kd_equivalent_molar"
    PPI_AFFINITY_PREDICTION = "ppi_affinity_prediction"
    ROSETTA_DG_SEPARATED_REU = "rosetta_dg_separated_reu"
    ROSETTA_DG_MINIMUM_REU = "rosetta_dg_minimum_reu"
    ROSETTA_PEPTIDE_BB_RMSD_ANGSTROM = "rosetta_peptide_bb_rmsd_angstrom"
    ROSETTA_INTERFACE_SCORE = "rosetta_interface_score"
    ROSETTA_REWEIGHTED_SCORE = "rosetta_reweighted_score"
    ROSETTA_INTERFACE_HBONDS = "rosetta_interface_hbonds"
    ROSETTA_BURIED_SURFACE_AREA = "rosetta_buried_surface_area"
